### ISSUE TITLE
Repeat NSP Install failed on Mac

### ISSUE THREAD

**Issue by luckscx** [fourminute/Fluffy#44]
Mac OS . Tinfoil USB install.
first install nsp(batch) after start python script is success
but next is always failed with exception.
here the stack 
```
ERROR:root:[Errno 13] Access denied (insufficient permissions)
Traceback (most recent call last):
  File "fluffy.pyw", line 1193, in init_tinfoil_usb_install
    Tinfoil.send_nsp_list(selected_files, nsp_dir, out_ep)
  File "fluffy.pyw", line 1168, in send_nsp_list
    out_ep.write(b'TUL0')
  File "/usr/local/lib/python3.7/site-packages/usb/core.py", line 387, in write
    return self.device.write(self, data, timeout)
  File "/usr/local/lib/python3.7/site-packages/usb/core.py", line 940, in write
    intf, ep = self._ctx.setup_request(self, endpoint)
  File "/usr/local/lib/python3.7/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/usb/core.py", line 216, in setup_request
    self.managed_claim_interface(device, intf)
  File "/usr/local/lib/python3.7/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/usb/core.py", line 167, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "/usr/local/lib/python3.7/site-packages/usb/backend/libusb1.py", line 811, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "/usr/local/lib/python3.7/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)
```

**Comment by fourminute** [comment]
Try running Fluffy with escalated permissions and restarting Tinfoil before another consecutive install. This issue does not happen on Windows or Linux.

**Comment by luckscx** [comment]
do restart tinfoil after every install works.
so it looks like tinfoil bug?  may be catch this exception and show some "do restart" message.
feel free to close this.

**Comment by luckscx** [comment]
and sudo python3 fluffy.pyw not working at all. so this error message has some mislead.

**Comment by fourminute** [comment]
Yes Tinfoil is known for this bug, it's unfortunate but at least it's well known. I'm glad you were able to resolve things. If you have any further issues you can feel free to make another issue! Have a good day.
