### ISSUE TITLE
Failed to send NSP.

### ISSUE THREAD

**Issue by lunalik2** [fourminute/Fluffy#45]
Here is the log:
DEBUG:root:Fluffy Log: If you see nothing here. Good!
ERROR:root:is_kernel_driver_active
Traceback (most recent call last):
  File "D:\Documents\Switch\pc\fluffy.pyw", line 898, in init_goldleaf_usb_install
    if dev.is_kernel_driver_active(0):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\usb\core.py", line 1064, in is_kernel_driver_active
    interface)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\usb\backend\__init__.py", line 365, in is_kernel_driver_active
    _not_implemented(self.is_kernel_driver_active)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\usb\backend\__init__.py", line 81, in _not_implemented
    raise NotImplementedError(func.__name__)
NotImplementedError: is_kernel_driver_active

**Comment by lunalik2** [comment]
Deleting the whole conditional (just the conditional, not the contents) worked fine for me, but I assume it exists for a purpose.

**Comment by lunalik2** [comment]
Nevermind doesn't work fine.

**Comment by fourminute** [comment]
This was fixed in 2.7.1

**Comment by lunalik2** [comment]
Oops, my bad.
