### ISSUE TITLE
install NSP error

### ISSUE THREAD

**Issue by Ricklin17** [fourminute/Fluffy#68]
select NSP file is ok.But when begin transfer both switch and fluffy get worng.and I can't upload log so I'll copy the info.Hope for answer.

log
DEBUG:root:Fluffy Log: If you see nothing here. Good!
ERROR:root:[Errno 32] Pipe error
Traceback (most recent call last):
  File "fluffy.pyw", line 1372, in init
    self.send_nsp_list()
  File "fluffy.pyw", line 1455, in send_nsp_list
    global_out.write(nsp_path)
  File "site-packages\usb\core.py", line 387, in write
  File "site-packages\usb\core.py", line 948, in write
  File "site-packages\usb\backend\libusb1.py", line 824, in bulk_write
  File "site-packages\usb\backend\libusb1.py", line 920, in __write
  File "site-packages\usb\backend\libusb1.py", line 595, in _check
usb.core.USBError: [Errno 32] Pipe error
ERROR:root:[Errno 32] Pipe error
Traceback (most recent call last):
  File "fluffy.pyw", line 1372, in init
    self.send_nsp_list()
  File "fluffy.pyw", line 1455, in send_nsp_list
    global_out.write(nsp_path)
  File "site-packages\usb\core.py", line 387, in write
  File "site-packages\usb\core.py", line 948, in write
  File "site-packages\usb\backend\libusb1.py", line 824, in bulk_write
  File "site-packages\usb\backend\libusb1.py", line 920, in __write
  File "site-packages\usb\backend\libusb1.py", line 595, in _check
usb.core.USBError: [Errno 32] Pipe error

**Comment by fourminute** [comment]
This is a very general error. I'll need more information.
