### ISSUE TITLE
usb.core.USBError: [Errno 75] Overflow

### ISSUE THREAD

**Issue by YoyPa** [fourminute/Fluffy#7]
Hello,
When trying to install nsp via tinfoil, I'm getting an overflow error:
```
$ ./fluffy.pyw     
Error: QDarkStyle not found. Using default.      # not related
REMOVED NAME [REMOVED ID][v0].nsp                # I removed title name/ID
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "./fluffy.pyw", line 619, in init_tinfoil_usb_install
    poll_commands(nsp_dir, in_ep, out_ep)
  File "./fluffy.pyw", line 571, in poll_commands
    cmd_header = bytes(in_ep.read(0x20, timeout=0))
  File "/usr/lib/python3.7/site-packages/usb/core.py", line 402, in read
    return self.device.read(self, size_or_buffer, timeout)
  File "/usr/lib/python3.7/site-packages/usb/core.py", line 988, in read
    self.__get_timeout(timeout))
  File "/usr/lib/python3.7/site-packages/usb/backend/libusb1.py", line 833, in bulk_read
    timeout)
  File "/usr/lib/python3.7/site-packages/usb/backend/libusb1.py", line 936, in __read
    _check(retval)
  File "/usr/lib/python3.7/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 75] Overflow
```
I correctly get dialog from tinfoil on the switch (Destination/IgnoreFirmware/Install)
When getting to the install screen(switch) the error pop(Linux).
Switch install screen:
```
Installing from /a path i'm too lazy to type/file.nsp
Retrieving remote NSP header...
Preparing install...
CNMT Name: ANumber.cnmt.nca
Installing ANumber.cnmt.nca to storage id 5
> Download Progress 0/0 MB (0%) (0.00 MB/s)
```

**Comment by fourminute** [comment]
Hmm, that is interesting. From both the official method and Fluffy? I think you should try to use the recommended Tinfoil.nro. 

Have you tried Safe Mode?

**Comment by YoyPa** [comment]
I feel stupid, using the tinfoil you provide solves it.
