### ISSUE TITLE
MacOS: USB install error - Tinfoil threw an exception

### ISSUE THREAD

**Issue by drshake12** [fourminute/Fluffy#70]
running Mojave OS
SXOS on 8.0.1 emunand
Tinfoil 1.61

Heres the log: 

ERROR:root:[Errno 13] Access denied (insufficient permissions)
Traceback (most recent call last):
  File "./fluffy.pyw", line 1372, in init
    self.send_nsp_list()
  File "./fluffy.pyw", line 1451, in send_nsp_list
    global_out.write(b'TUL0')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/usb/core.py", line 387, in write
    return self.device.write(self, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/usb/core.py", line 940, in write
    intf, ep = self._ctx.setup_request(self, endpoint)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/usb/core.py", line 216, in setup_request
    self.managed_claim_interface(device, intf)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/usb/core.py", line 167, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/usb/backend/libusb1.py", line 811, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)

**Comment by fourminute** [comment]
Insufficient permissions. Try running elevated? I don't use a Mac, or own one. But it should be a fairly simple fix I'd assume.

**Comment by krekeroff90** [comment]
Mojave OS 10.14.5
Atmo 8.0.1
Tinfoil 1.61

I've the same problem
If I use DBI instead of Tinfoil, I don't get errors, but my transfer rate is 0.05-0.2 MB/s

**Comment by drshake12** [comment]
I loaded the tinfoil version recommended by fluffy in addition to the 1.61. That’s how I got it to work as it’s supposed to. Try that. 
For some reason, the tinfoil/hbg version we were using doesn’t work with fluffy

**Comment by lookye** [comment]
Tinfoil made by blawar is not supported by Fluffy.
Use the original tinfoil made by Adubbz. It is also available to download in the Fluffy repo.
