### ISSUE TITLE
Transfer failure using Tinfoil

### ISSUE THREAD

**Issue by CorgiZack** [fourminute/Fluffy#74]
OFW: 8.1.0
CFW: Atmosphere 0.9.2
Tinfoil 0.2.1
Fluffy: 2.9.2 (.pyw)
Windows 10 (1903)

Switch:
Launch Tinfoil > Title Management > Network Install NSP
Switch IP is 192.168.1.xxx
Waiting for connection...
Press B to cancel

Windows:
Launch Fluffy > Select Tinfoil > Select Network
Set Switch IP
Set Computer IP
Click NSP Selection button
Select any NSP, Open
Click Begin Transfer
Headers Sent
Awaiting Connection Request

Switch:
Press X to toggle on single selection
Press A to continue
Select Destination = SD Card
An error occurred
PerformRequest:71: Failed to retrieve HTTP Header: Server returned nothing (no headers, no data)

Press any button to exit.
Press B

System crash!
Error code: 2168-0002 (0x4a8)
Title: 010000000000100D
Firmware: 8.1.0 (Atmosphere 0.9.2-master-0d840e19)

An error has occured.
etc.

Nothing is added to the log file during these events.

NOTE: This actually runs fine if I launch it through IDLE! So whatever is different about that environment, possibly error handling(?), allows it to function.

**Comment by CorgiZack** [comment]
Oh man, don't hate me for this dump:

Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
======================== RESTART: F:\__NX\fluffy.pyw ========================
Successfully loaded config: 'F:\__NX/fluffy.conf'
192.168.1.162 - - [09/Jul/2019 02:23:02] "HEAD /7133386.nsp HTTP/1.1" 200 -
192.168.1.162 - - [09/Jul/2019 02:23:02] "GET /7133386.nsp HTTP/1.1" 206 -
----------------------------------------
Exception happened during processing of request from ('192.168.1.162', 62035)
Traceback (most recent call last):
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 646, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 426, in handle
    self.handle_one_request()
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 414, in handle_one_request
    method()
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 653, in do_GET
    self.copyfile(f, self.wfile)
  File "F:\__NX\fluffy.pyw", line 1372, in copyfile
    outfile.write(buf)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 799, in write
    self._sock.sendall(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
----------------------------------------
192.168.1.162 - - [09/Jul/2019 02:23:02] "GET /7133386.nsp HTTP/1.1" 206 -
----------------------------------------
Exception happened during processing of request from ('192.168.1.162', 57837)
Traceback (most recent call last):
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 646, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 426, in handle
    self.handle_one_request()
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 414, in handle_one_request
    method()
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 653, in do_GET
    self.copyfile(f, self.wfile)
  File "F:\__NX\fluffy.pyw", line 1372, in copyfile
    outfile.write(buf)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 799, in write
    self._sock.sendall(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
----------------------------------------
192.168.1.162 - - [09/Jul/2019 02:23:02] "GET /7133386.nsp HTTP/1.1" 206 -
----------------------------------------
Exception happened during processing of request from ('192.168.1.162', 63039)
Traceback (most recent call last):
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 646, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 426, in handle
    self.handle_one_request()
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 414, in handle_one_request
    method()
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 653, in do_GET
    self.copyfile(f, self.wfile)
  File "F:\__NX\fluffy.pyw", line 1372, in copyfile
    outfile.write(buf)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 799, in write
    self._sock.sendall(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
----------------------------------------
192.168.1.162 - - [09/Jul/2019 02:23:03] "GET /7133386.nsp HTTP/1.1" 206 -
----------------------------------------
Exception happened during processing of request from ('192.168.1.162', 33927)
Traceback (most recent call last):
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 646, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 426, in handle
    self.handle_one_request()
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 414, in handle_one_request
    method()
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 653, in do_GET
    self.copyfile(f, self.wfile)
  File "F:\__NX\fluffy.pyw", line 1372, in copyfile
    outfile.write(buf)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 799, in write
    self._sock.sendall(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
----------------------------------------
192.168.1.162 - - [09/Jul/2019 02:23:03] "GET /7133386.nsp HTTP/1.1" 206 -
----------------------------------------
Exception happened during processing of request from ('192.168.1.162', 53156)
Traceback (most recent call last):
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 646, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 426, in handle
    self.handle_one_request()
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 414, in handle_one_request
    method()
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 653, in do_GET
    self.copyfile(f, self.wfile)
  File "F:\__NX\fluffy.pyw", line 1372, in copyfile
    outfile.write(buf)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 799, in write
    self._sock.sendall(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
----------------------------------------
192.168.1.162 - - [09/Jul/2019 02:23:04] "GET /7133386.nsp HTTP/1.1" 206 -
----------------------------------------
Exception happened during processing of request from ('192.168.1.162', 43936)
Traceback (most recent call last):
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 646, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 426, in handle
    self.handle_one_request()
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 414, in handle_one_request
    method()
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 653, in do_GET
    self.copyfile(f, self.wfile)
  File "F:\__NX\fluffy.pyw", line 1372, in copyfile
    outfile.write(buf)
  File "C:\Users\dsp47\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 799, in write
    self._sock.sendall(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
----------------------------------------
192.168.1.162 - - [09/Jul/2019 02:23:08] "GET /7133386.nsp HTTP/1.1" 206 -
192.168.1.162 - - [09/Jul/2019 02:23:08] "GET /7133386.nsp HTTP/1.1" 206 -
